version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://zerodice0:890421@host.docker.internal:5432/your_database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    # 데이터베이스가 준비될 때까지 대기
    depends_on:
      - db
  
  # 개발 환경에서만 사용할 PostgreSQL 컨테이너 (옵션)
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=zerodice0
      - POSTGRES_PASSWORD=890421
      - POSTGRES_DB=your_database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 